name: Code lint
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Ktlint Checks
        run: ./gradlew ktlintCheck

      - name: Detekt
        run: ./gradlew detekt
